### ISSUE TITLE
staticClick is firing when scrolling

### ISSUE THREAD

**Issue by sjelfull** [metafizzy/flickity#123]
I'm experiencing that if the slides is taking the whole height of the viewport, and i'm scrolling while draggable is set to true, staticClick will start firing.

See test here: http://codepen.io/sjelfull/pen/oXXZXJ

Seeing this in Safari/Chrome on iOS 8.

**Comment by Odisseas** [comment]
I can confirm this on the latest Chrome/Android too

**Comment by xenohawk** [comment]
Currently I use this to check if it is a vertical scrolling when staticClick fired and this temp fix this issue.

```javascript
var lastposition;
flkty.on( 'pointerDown', function( event, pointer ) {  
  lastposition = pointer.pageY;  
});
flkty.on( 'staticClick', function( event, pointer, cellElement, cellIndex ) { 
  // dismiss if it is scrolling down
  if ( lastposition !== pointer.pageY ) { return; }  
});
```

**Comment by desandro** [comment]
Thanks for reporting this issue — and putting together the test case! Sorry I didn't catch this earlier.

This has been fixed in Flickity v1.1.1. [Try it out!](http://flickity.metafizzy.co/) :pear:

The fix involved listening for scroll events after pointer is down. If scroll moves more than 3 pixels, the tap/click event is canceled so staticClick isn't triggered.

**Comment by mnmldr** [comment]
Seems that the problem is still there.

https://time.sc/lodging/mercure_arbat_moscow - please try touch scrolling this page starting with a tap/push at the photo and releasing the tap right away - the scroll does work in this case (inertial scroll), but a fullscreen photo is shown (that's a reaction to staticClick). I believe the tap is over before 3 pixels scroll, as I quickly release the finger, but it's still a scroll for a touch device. So probably the 3 pixels threshold is not a very accurate fix.

**Comment by bfredtim** [comment]
Did this bug come back in Flickity 2?
