### ISSUE TITLE
Flickity not initializing properly with deferred/async script tag

### ISSUE THREAD

**Issue by vetruvet** [metafizzy/flickity#441]
If Flickity's script is loaded through a script tag with the `defer` or `async` attribute, it will not initialize properly. Specifically, with default options, the page dots, prev/next controls, and dragging functionality are not initialized, but navigating the carousel with arrow keys still works. Taking the `defer`/`async` attribute off of the script tag fixes the problem.

fiddle showing problem (with defer attribute): https://jsfiddle.net/ejj63ct0/

Any idea what could be causing this problem?

I've confirmed this behavior in latest Chrome on Linux and OS X, Firefox on Linux and OS X, and Safari.

**Comment by desandro** [comment]
Thank you for reporting this issue. This looks like a legitimate bug. I'll have to investigate.

**Comment by desandro** [comment]
Looks like the issue was a race condition with `fizzyUIUtils.docReady`. It immediately executes if the document is ready. So Flickity modules were not added before the instance was initialized.

I've pushed a fix in fizzy-ui-utils. This issue will be fixed in the next release.  Thanks so much for reporting this bug!

**Comment by vetruvet** [comment]
Thanks for the quick fix!!

**Comment by ArshdeepSoniYell** [comment]
Has this issue been fixed in 2.0.3 or is there a release still pending for this fix?

**Comment by desandro** [comment]
This has been fixed in [Flickity v2.0.4](https://github.com/metafizzy/flickity/releases/tag/v2.0.4)

**Comment by tal3nce** [comment]
Hi, I still have this exact same issue. I use Laravel and Vue in my project and the only way to make it work is to put my compiled app.js file in the bottom of the body tag. 

If I put it the head tag with defer/async it doesn't work until I resize the viewport. On load the viewport height is randomly small so every element in the carousel is weirdly overlapped and overflowing parts are cut off and it pops into place as soon as I resize the window by a few pixels. 

![flickity-bug](https://user-images.githubusercontent.com/28575258/85211597-ee964a00-b34a-11ea-831c-13ad0486123b.JPG)


Here's my master Laravel Blade file:

```
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script defer src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    {{--<link rel="dns-prefetch" href="//fonts.gstatic.com">--}}
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">


    <!-- Styles -->
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">

</head>
<body>


<div id="app">
    {{ $slot }}
</div>


{{--<script src="{{ asset('js/app.js') }}"></script>--}}

</body>
</html>
```

And the Carousel.vue component:

```
<template>
    <div>
        <slot></slot>
    </div>
</template>

<script>
    import Flickity from 'flickity';
    import 'flickity/dist/flickity.min.css';

    export default {
        props: {
            autoPlay: { default: false },
            cellAlign: { default: "center" },
            pageDots: { default: true },
            wrapAround: { default: true }
        },
        mounted() {
            new Flickity(this.$el, {
                autoPlay: this.autoPlay,
                cellAlign: this.cellAlign,
                pageDots: this.pageDots,
                wrapAround: this.wrapAround,
            });
        },
    }
</script>
```






I use v2.2.1, the issue is seen on Chrome, Opera and Edge, I haven't tested other browsers.
