### ISSUE TITLE
Flickity Interaction Causes mobile chrome viewport height to stop recalculating when URL bar shows and hides

### ISSUE THREAD

**Issue by eugenecyckowski** [metafizzy/flickity#725]
**The Issue**
There is an issue on mobile Android Chrome where after interacting with Flickity, the viewport height stops recalculating when the browser url bar shows and hides.

**Steps to Reproduce**
1. After loading the page on mobile chrome browser with the url bar shown, in the console check viewport height by running `window.innerHeight`.
2. Without touching the carousel, scoll the page down so that the mobile browser URL bar hides.
3. Run `window.innerHeight` again and observe that the `innerHeight` has increased.
4. Interact with the carousel by swiping the cells.
5. Now run `window.innerHeight` with the URL bar showing and with it hiding. Observe that this value is no longer updating when the URL bar shows and hides.

**The Impact**
After interacting with Flickity, elements that are expected to fill 100% of the screen height will not update when the URL bar shows and hides. This results in either empty space at the bottom of the screen when the calculated height is smaller than the current actual height, or elements that should be positioned on the bottom of the screen being pushed off screen and unaccessible when the calculated height is larger than the current actual height.

**Demo**
See the Codepen demo below to test the issue.
https://codepen.io/eugenecyckowski/pen/jzYJBm?editors=1100

**Comment by theenoahmason** [comment]
@eugenecyckowski @desandro I can confirm this issue! I was just about to post this exact problem.

This causes any elements that are fixed to the window with height 100% to behave improperly.

If the first swipe on flickity happens when Chrome mobile's addreas bar is in view, then all full height fixed elements will not reach the end of the viewport. If the first swipe happens with Chrome mobile's address bar is hidden, then all full height fixed elements will pass the viewport.

The reason this is happening is because Chrome is not able to recalculate the height of the window.

I have not looked at the source code, but intuition tells me this has to do with a touch event not ending. It seema chrome waits for the touch event to end before it does the recalculation.

**Comment by theenoahmason** [comment]
@desandro thanks!

It is affecting all our modals, and nav drawers, etc. A fix, or even a small hack snippet would be extremely appreciated! 

I am going to try messing with the drag threshhold property to see if that does anything, just a hunch. will post update in a few. 

I will be up working for the next few hours of you would like me to test anything as I am currently working on a site where this issue is readily apparent and consistent.

**Comment by eugenecyckowski** [comment]
I second @theenoahmason that its effecting all modals, nav drawers etc. 

Still no luck on our end fixing the issue. We're going to try a couple things this week too and will share if we find a solution.

@desandro if you do find any solution please share!

**Comment by theenoahmason** [comment]
@eugenecyckowski This may not be Ideal, but here is what we did for now (CSS Only):

We made all full height elements (dialog backdrops, drawers, etc.) use `height: 100vh;` (device height). 

**This is the height of the viewport without chrome's URL bar (everything under the notification bar), and  does not get recalculated when  chrome's URL bar is hidden/shown.** 

The reason this was more desirable:
Now, no drawers, dialogs are ever *shorter* than the viewport.

The reason this is not ideal:
Now, To reach the bottom of a drawer, for example, you must scroll and hide the URL bar. This also bumps down dialogs that should be centered vertically by the same height as the URL bar. It is still fully accessible.

**Comment by desandro** [comment]
Sorry, haven't had a chance to dig into this one. Considering that Flickity v2.1 just launched, have you tried falling back to v2.0 and seeing if this issue persists? See demo: https://codepen.io/desandro/pen/GxBxZy

**Comment by shaylevi2** [comment]
Complete showstopper, what an horrendous bug.

Did anyone find a solution?

**Comment by theenoahmason** [comment]
@desandro I don't know if this helps pinpoint the issue, but I can confirm that this is only effecting chrome.

Samsung internet app has a similar recalculation of the viewport for their address bar/bottom bar on scroll. This issue does _NOT_ appear in this app. 

This appears to be isolated to chrome mobile. Interested in knowing if this happens on chrome in ios?

**Comment by theenoahmason** [comment]
@shaylevi @eugenecyckowski 

What device/browser is this affecting for you? can you confirm this issue persists on chrome for ios?

**Comment by eugenecyckowski** [comment]
@theenoahmason 

we're also seeing the issue on iOS Chrome (confirmed on a few different iPhone devices), and have the issue on all the android devices running chrome that we've tested on. Looks like the issue is happening on both iOS and Android Chrome.

**Comment by theenoahmason** [comment]
@eugenecyckowski Thanks for checking that out.

I can confirm this issue does not persist in Firefox for android. 

This is clearly only a chrome bug. At this point I'm lost.

**Comment by mleone** [comment]
This was a complete showstopper for my team; we ended up having to switch to https://github.com/nolimits4web/swiper/ . Nonetheless, props to flickity contributors for all the hard work! We'd be open to trying out flickity again if this issue gets addressed.

**Comment by theenoahmason** [comment]
@desandro I just experienced this issue with another script, not using flickity on said project at all. 

**For reference:**
Using Google's MDC Web (Material Design Components for the Web). The drawer (MDCTemporaryDrawer) is slideable on touch devices; interacting with that slideable drawer, then scrolling the viewport causes the same artifacts as described in this issue.

What this means for me is that this is a chrome issue.

@mleone can you confirm you were only seeing this issue in chrome mobile?

**Comment by joeytrout** [comment]
I've been on this bug for a while with a different plugin and have pin pointed it to Android Chrome not being able to handle the css "touch-action: pan-y". If you put this css on ANY element on the page and swipe left or right, it will cause this issue.

**Comment by theenoahmason** [comment]
@desandro This issue is fixed as of latest chrome android update. It seems touch-action prop is now safe to use.

Party on, party people.

**Comment by HanaXu** [comment]
I'm still getting this issue on iOS Chrome, is the issue only fixed for android?
